export const registerFormControl = [
	{
		name: "fullName",
		label: "Full Name",
		placeholder: "Enter your full name",
		componentType: "input",
		type: "text",
	},
	{
		name: "email",
		label: "Email",
		placeholder: "Enter your Email",
		componentType: "input",
		type: "email",
	},
	{
		name: "phone",
		label: "Phone",
		placeholder: "Enter your Phone No.",
		componentType: "input",
		type: "tel",
	},
	{
		name: "password",
		label: "Password",
		placeholder: "Enter your password",
		componentType: "input",
		type: "password",
	},
];

export const loginFormControl = [
	{
		name: "email",
		label: "Email",
		placeholder: "Enter your Email",
		componentType: "input",
		type: "email",
	},
	{
		name: "password",
		label: "Password",
		placeholder: "Enter your password",
		componentType: "input",
		type: "password",
	},
];
export const ALL_SPECIALIZATIONS = [
	{ id: "pediatrics", label: "Pediatrics" },
	{ id: "cardiology", label: "Cardiology" },
	{ id: "dermatology", label: "Dermatology" },
	{ id: "gastroenterology", label: "Gastroenterology" },
	{ id: "endocrinology", label: "Endocrinology" },
	{ id: "neurology", label: "Neurology" },
	{ id: "oncology", label: "Oncology" },
	{ id: "pulmonology", label: "Pulmonology" },
	{ id: "orthopedic-surgery", label: "Orthopedic Surgery" },
	{ id: "ophthalmology", label: "Ophthalmology" },
	{ id: "otolaryngology-ent", label: "Otolaryngology (ENT)" },
	{
		id: "obstetrics-gynecology-obgyn",
		label: "Obstetrics and Gynecology (OB/GYN)",
	},
	{ id: "psychiatry", label: "Psychiatry" },
	{ id: "urology", label: "Urology" },
	{ id: "nephrology", label: "Nephrology" },
	{ id: "general-surgery", label: "General Surgery" },
	{ id: "anesthesiology", label: "Anesthesiology" },
	{ id: "radiology", label: "Radiology" },
];
export const timeSlots = [
	"8:00-8:30",
	"8:30-9:00",
	"9:00-9:30",
	"9:30-10:00",
	"10:00-10:30",
	"10:30-11:00",
	"11:00-11:30",
	"11:30-12:00",
	"12:00-12:30",
	"12:30-1:00",
	"1:00-1:30",
	"1:30-2:00",
	"2:00-2:30",
	"2:30-3:00",
	"3:00-3:30",
	"3:30-4:00",
	"4:00-4:30",
	"4:30-5:00",
	"5:00-5:30",
	"5:30-6:00",
	"6:00-6:30",
	"6:30-7:00",
	"7:00-7:30",
	"7:30-8:00",
];
export const documentTypes = [
	"Medical License",
	"Board Certification",
	"Insurance Certificate",
	"CV/Resume",
	"Education Certificate",
	"Training Certificate",
	"Other",
];
export const daysOfWeek = [
	"Monday",
	"Tuesday",
	"Wednesday",
	"Thursday",
	"Friday",
	"Saturday",
	"Sunday",
];
